import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>IMCD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a>IMCD</a>
        </h1>

        <div className={styles.grid}>
          <p>TEXT DE PRESENTACIÓ</p>
        </div>
      </main>

      <footer className={styles.grid}>
        <Link href="/register">
          <button className={styles.button}>Register</button>
        </Link>
      </footer>
    </div>
  );
}
